### ISSUE TITLE
relation between "influxdb:query" and "slurmctld:influxdb-api"

### ISSUE THREAD

**Issue by mmrezaie** [omnivector-solutions/slurm-bundles#20]
When trying to add ./slurm-addons/monitoring.yaml and ./slurm-addons/influxdb.yaml I get this error inwhich influxdb doesn't have the relation.

The error is:
'ERROR cannot deploy bundle: cannot add relation between "influxdb:query" and "slurmctld:influxdb-api": application "slurmctld" has no "influxdb-api" relation'

I tried this 'juju deploy' on the master branch.

Even deploying influxdb and then adding relation gets me the same error as well.

**Comment by mmrezaie** [comment]
Although I see that @heitorPB is working on it. So maybe I should close this.

**Comment by heitorPB** [comment]
Hello,

The InfluxDB relation is currently only available on the `edge` channel of the charms, so you should also use the `slurm-core/charms/latest-edge.yaml` overlay (modify as needed):

```bash
$ juju deploy ./slurm-core/bundle.yaml \
               --overlay ./slurm-core/clouds/lxd.yaml \
               --overlay ./slurm-core/series/centos7.yaml \
               --overlay ./slurm-core/charms/latest-edge.yaml
```

Let me know how it goes!

**Comment by mmrezaie** [comment]
It makes since. Thank you. But now I am getting this error:

- upload charm slurmctld from charm-hub for series centos7 from channel latest/edge with architecture=amd64
ERROR cannot deploy bundle: cannot add charm "slurmctld": revision-not-found: No revision was found in the Store.

if I use seriese/focal.yaml I get this:
- add relation node-exporter:juju-info - percona-cluster:juju-info
ERROR cannot deploy bundle: cannot add relation between "node-exporter:juju-info" and "percona-cluster:juju-info": cannot add relation "node-exporter:juju-info percona-cluster:juju-info": principal and subordinate applications' series must match

**Comment by mmrezaie** [comment]
Oh forget about it. I tried to add monitoring to it as well. It works with only influxdb charm.

**Comment by mmrezaie** [comment]
Can you do 'juju deploy influxdb' and not get permission error?

**Comment by heitorPB** [comment]
> Oh, forget about it ;-). I tried to add monitoring to it as well. It works with only influxdb charm. The problem is with monitoring added.

Unfortunately this is a [bug in Charmhub](https://bugs.launchpad.net/snapstore-server/+bug/1938567) :( 


> Can you do 'juju deploy influxdb' and not get permission error in influxdb container?

what do you mean?

You can also have a normal deploy and `juju deploy influxdb` and then `juju relate slurmctld influxdb`. What error you see?

**Comment by mmrezaie** [comment]
Yeah I am doing the same but I get a permission error inside the influxdb container. This error:

influxdb.service: Failed at step EXEC spawning /usr/lib/influxdb/scripts/influxd-systemd-start.sh: Permission denied

This is not related to slurm charm. But I think it is a latest bug in influxdb.

I created a seperate model and just did the `juju deploy influxdb`. I get this message from juju: `hook failed: "install"` , and inside the container I get his error from systemd:
`influxdb.service: Failed at step EXEC spawning /usr/lib/influxdb/scripts/influxd-systemd-start.sh: Permission denied`

So something is wrong with either influxdb charm or something else. I will see if I can report the error to them.
