### ISSUE TITLE
LICENSE file missing

### ISSUE THREAD

**Issue by dlaehnemann** [omnivector-solutions/slurm-bundles#33]
Just wanted to note, that the `LICENSE` file mentioned in the main `README.md` does not exist (it does in the `slurm-charms` repo):

https://github.com/omnivector-solutions/slurm-bundles/blob/6c43f88cf8c6a8dda2c8cff84c8bce7377e27438/README.md?plain=1#L45

**Comment by jaimesouza** [comment]
Hi @dlaehnemann! Thank you for contacting us! We will fix that.
