### ISSUE TITLE
Try deploy bundle : Version Edge on Jammy 

### ISSUE THREAD

**Issue by moula** [omnivector-solutions/slurm-bundles#35]
Hi, I am trying to deploy Edge version on Ubuntu Jammy.
 I go through the bundle and not by charm locally. Which allows me to tune according to my nodes tagged on MAAS 3.4. 
The problem comes from cluster mysql. I thought it was migrated by @NucciTheBoss.
Can I test it with on focal or jammy or is it still not possible? 
Thanks.
![Capture d’écran du 2023-04-29 09-38-35](https://user-images.githubusercontent.com/1804815/235291228-1ffa5676-4c5e-435a-add2-28ebe1bf1b90.png)
![Capture d’écran du 2023-04-29 09-38-00](https://user-images.githubusercontent.com/1804815/235291231-0282c18c-be36-41ed-b571-f556f883e9c5.png)

**Comment by NucciTheBoss** [comment]
Hi @moula 

The initial migration is complete, but I do not believe this bundle has been updated to reflect recent changes. You need to deploy the new MySQL charm over Percona cluster:

```
juju deploy mysql
juju deploy mysql-router slurmdbd-router --channel dpe/edge
juju integrate mysql:database slurmdbd-router:backend-database
juju integrate slurmdbd:database slurmdbd-router:database
```

After a few minutes the slurmdbd node should connect itself to the MySQL instance. Let me know if you have any issues.

**Comment by moula** [comment]
@NucciTheBoss Thank you. As soon as I have some time I will modify the percona node as you suggested.
 Right now I'm on microk8s and the different models ( kubeflow, mysql, kafka, cos...).
